
SRC_FILES += sig_agent/sig_agent_pkg.sv
SRC_FILES += sig_agent/sig_if.sv
SRC_FILES += xyz_agent/xyz_agent_pkg.sv
SRC_FILES += xyz_agent/xyz_if.sv
SRC_FILES += test_lib_pkg.sv
SRC_FILES += dut_if.sv

all : run_my_test run_random_test run_full_random_test

include ../common.mk